#ifndef CHADTP_STATUS_CODES_H
#define CHADTP_STATUS_CODES_H

char *get_status_code_name(unsigned int);

#define CHADTP_OK 200
#define CHADTP_CREATED 201
#define CHADTP_ACCEPTED 202
#define CHADTP_NO_CONTENT 204
#define CHADTP_MOVED_PERMANENTLY 301
#define CHADTP_MOVED_TEMPORARILY 302
#define CHADTP_NOT_MODIFIED 304
#define CHADTP_BAD_REQUEST 400
#define CHADTP_UNAUTHORIZED 401
#define CHADTP_FORBIDDEN 403
#define CHADTP_NOT_FOUND 404
#define CHADTP_INTERNAL_SERVER_ERROR 500
#define CHADTP_NOT_IMPLEMENTED 501
#define CHADTP_BAD_GATEWAY 502
#define CHADTP_SERVICE_UNAVAILABLE 503

#endif
